---
title: "Image 1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
dataSet <- data.frame(
  time=timeX,
  y_us=Y$US,
  y_emerging=Y$EmergingEconomies,
  y_britain=Y$Britain,
  y_japan=Y$Japan,
  y_china=Y$China,
  y_advanced=Y$AdvancedEconomy
)
```

```{r}
timeX = c(2010, 2015, 2021)
```


```{r}
timeX2 = lubridate::ymd(c("2010-01-01", "2015-01-01", "2020-01-01"))
timeX2
```


```{r}
Y <- list()
Y$US <- c(58, 60, 76)
Y$EmergingEconomies <- c(52, 90, 100)
Y$Britain <- c(90, 70, 77)
Y$Japan <- c(110, 90, 120)
Y$China <- c(120, 160, 162)
Y$AdvancedEconomy <- c(90, 90, 100)

size=1
ggplot() +
  geom_line(
    aes(
      x=timeX,
      y=Y$AdvancedEconomy
      ),
    size=size,
    color="#963d4d"
    ) +
  geom_line(
    aes(
      x=timeX,
      y=Y$US
    ),
    size=size,
    color="#066da0"
  ) +
  geom_line(
    aes(
      x=timeX,
      y=Y$Britain
    ),
    size=size,
    color="#71cac6"
  ) +
  geom_line(
    aes(
      x=timeX,
      y=Y$EmergingEconomies
    ),
    size=size,
    color="#ae8c97"
  ) +
  geom_line(
    aes(
      x=timeX,
      y=Y$Japan
    ),
    size=size,
    color="#30c1d3"
  ) + 
  geom_line(
    aes(
      x=timeX,
      y=Y$China
    ),
    size=size,
    color="#f15c41"
  )

#30c1d3
#f15c41
```

```{r}
dataSet <- data.frame(
  time=timeX,
  y_us=Y$US,
  y_emerging=Y$EmergingEconomies,
  y_britain=Y$Britain,
  y_japan=Y$Japan,
  y_china=Y$China,
  y_advanced=Y$AdvancedEconomy
)
size=1
ggplot(
  data=dataSet,
  aes(x=time)
) +
  geom_line(
    aes(
      y=y_advanced
      ),
    size=size,
    color="#963d4d"
    ) +
  geom_line(
    aes(
      y=y_us
    ),
    size=size,
    color="#066da0"
  ) +
  geom_line(
    aes(
      y=y_britain
    ),
    size=size,
    color="#71cac6"
  ) +
  geom_line(
    aes(
      y=y_emerging
    ),
    size=size,
    color="#ae8c97"
  ) +
  geom_line(
    aes(
      y=y_japan
    ),
    size=size,
    color="#30c1d3"
  ) + 
  geom_line(
    aes(
      y=y_china
    ),
    size=size,
    color="#f15c41"
  )

```

```{r}
date = c(2005, 2010,2012, 2015,2020,2021)
data = list()
data$china <-
data.frame(
date = date,
y = c(110,80,120,160,150,150)
)
data$Japan <-
data.frame(
date = date,
y = c(100, 102, 110, 95,100,110)
)

ggplot(
mapping=aes(
x=date,
y=y
))+
geom_line(
data=data$Japan,
color="#2fc1d3gg",#input$color
size=3
)+
geom_line(
data=data$china,
color="#f2593d",
size=3
)
```

```{r}
dataSet |>
  tidyr::pivot_longer(cols=y_us:y_advanced, names_to = "country", values_to = "y") |>
  dplyr::arrange(country)-> 
  dataSet2
```

```{r}
tidyr::pivot_wider
```


```{r}
ggplot(
  data=dataSet2
) +
  geom_line(
    mapping= aes(
      x=time,
      y=y,
      group=country, 
      linetype=country # ignore group
    )
  )
```

